version: '3.9'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    working_dir: /sub
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/sub:/sub
    ports:
      - 1883:1883
      - 8080:8080
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
       MYSQL_USER: awin
       MYSQL_PASSWORD: awin
       MYSQL_ROOT_PASSWORD: awin
       MYSQL_DATABASE: nilm
       MYSQL_ROOT_HOST: '%'
    volumes:
       - ./sql:/var/lib/mysql
    ports:
       - 3306:3306
  mongo:
    image: mongo:4.4.17
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: sinew
       MONGO_INITDB_ROOT_PASSWORD: sinew3612
       MONGO_INITDB_DATABASE: nilm
    volumes:
       - ./mongo/db:/data/db
       - ./mongo/mongod.conf:/etc/mongod.conf
    ports:
       - 27018:27017
    network_mode: "host"
    command: mongod --auth -f /etc/mongod.conf
  web-api-1:
    restart: always
    build:
       context: ./flask
       dockerfile: Dockerfile
    ports:
       - 8088:5000
    network_mode: "host"
    depends_on:
       - db
       - mongo
  web-api-2:
    restart: always
    build:
       context: ./django
       dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
       - 8000:8000
    network_mode: "host"
    volumes:
       - ./django:/api
    depends_on:
       - db
       - mongo
  web-nginx:
    restart: always
    build:
       context: ./web
       dockerfile: Dockerfile
    ports:
       - 80:80
    network_mode: "host" 
    depends_on:
       - mosquitto
  sub:
    restart: always
    build:
       context: ./sub
       dockerfile: Dockerfile
    depends_on:
       - db
       - mosquitto
       - mongo
volumes:
  config:
  data:
  log:
  db:
  sql:
  django:
